name: dbt CI/CD

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: prc
    env:
      DBT_HOST: ${{ secrets.DBT_HOST }}
      DBT_HTTP_PATH: ${{ secrets.DBT_HTTP_PATH }}
      DBT_TOKEN: ${{ secrets.DBT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install dbt-databricks
      - name: Build (dev)
        if: github.ref == 'refs/heads/dev' || github.event_name == 'pull_request'
        run: dbt build --profiles-dir . --target dev
      - name: Build (prod)
        if: github.ref == 'refs/heads/main'
        run: dbt build --profiles-dir . --target prod